import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'nodejs-course',
    {
      type: 'category',
      label: 'Node.js Zero→Hero',
      collapsed: false,
      link: {type: 'doc', id: 'nodejs-zero-to-hero/nodejs-zero-to-hero'},
      items: ['nodejs-zero-to-hero/module-1/nodejs-zero-to-hero-module-1'],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'modules'}],
    },
  ],
};

export default sidebars;
